name: robotkernel
channels:
  - conda-forge
dependencies:
  - opencv
  - python >=3.6,<3.8.0a0
  - jupyterlab >=1.2.4,<1.3
  - nodejs >=11,<12
  - pip
  - pip:
    - matplotlib==3.1.2
    - pillow==6.2.1
    - requests==2.22.0
    - RESTinstance==1.0.2
    - robotframework==3.1.2
    - robotframework-faker==4.2.0
    - robotframework-seleniumlibrary==4.1.0
    - robotframework-seleniumscreenshots==0.9.5
    - selenium==3.141.0
    - urllib3==1.25.3
    - jupyter-starters==0.2.0a0
